# A= 1 * 1000 형렬 Z =1000*1 행렬 두 행렬의 곱과 합을 표현 하시오

In [108]:
import numpy as np
import random
import time
from scipy import special

In [51]:
# 일반 for 문돌려서 만드는거 행렬이기떄문에 [안에 for 문]
z=[random.random() for i in range(0,1000)]
x=[random.random() for i in range(0,1000)]
print(len(x),len(z))

1000 1000


In [52]:
start = time.time()  

sum = 0
for i in range(0,len(z)): # lne(z) 길이만큼 포문 돌려주는거 그래서 len  쓴다
    sum =sum + (z[i] * x[i])

end = time.time()
duration= end - start # 코드 돌리는데 걸리는 시간 계산

print(sum)
print(duration)

243.0994833513487
0.0009958744049072266


In [26]:
# numpy로 만드는 방법
z=np.random.rand(1,1000)
x=np.random.rand(1,1000)
print(z.shape,x.shape)

(1, 1000) (1, 1000)


In [54]:
start = time.time()  

c=np.dot(x,z)

end = time.time()
duration= end - start # 코드 돌리는데 걸리는 시간 계산

print('vectorized version:' + duration +'ms')

TypeError: can only concatenate str (not "float") to str

In [57]:
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c = np.dot(a,b)
toc=time.time()

print('vectorized version:' + str(1000*(toc-tic))+ 'ms')

vectorized version:0.9977817535400391ms


249600.92973022407

In [63]:
c=0
tic=time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print('for loop:'+ str(1000*(toc-tic))+ 'ms')

for loop:485.75615882873535ms


In [ ]:
# =	왼쪽 변수에 오른쪽 값을 할당한다	c = a + b → c = a + b
# +=	왼쪽 변수에 오른쪽 값을 더하고 결과를 왼쪽변수에 할당	c += a → c = c + a
# -=	왼쪽 변수에서 오른쪽 값을 빼고 결과를 왼쪽변수에 할당	c -= a → c = c - a
# *=	왼쪽 변수에 오른쪽 값을 곱하고 결과를 왼쪽변수에 할당	c *= a → c = c * a
# /=	왼쪽 변수에서 오른쪽 값을 나누고 결과를 왼쪽변수에 할당	c /= a → c = c / a
# %=	왼쪽 변수에서 오른쪽 값을 나눈 나머지의 결과를 왼쪽변수에 할당	c %= a → c = c % a
# **=	왼쪽 변수에 오른쪽 값만큼 제곱을 하고 결과를 왼쪽변수에 할당	c **= a → c = c ** a
# /=	왼쪽 변수에서 오른쪽 값을 나눈 몫의 결과를 왼쪽변수에 할당	c //= a → c = c // a

In [ ]:
# 되도록이면 for 문을 사용하지말고
# 다른 코드를 활용해서 하는게 속도도빠르고 훨씬 깔끔하다

# 신경망 만들기

step 1. 기본클래스 만들기
-구조정의
-학습
-추론

In [125]:
class MyNeuralNet :
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # 입력 , 은닉 ,출력 ,계층의 노드 개수 설정
        self.innode = inputnodes
        self.hnode = hiddennodes
        self.outnode = outputnodes
        
        # 학습률
        self.lr = learningrate
        
        self.wih = (np.random.rand(self.hnode, self.innode) - 0.5)
        self.who = (np.random.rand(self.outnode, self.hnode) - 0.5)
        
        pass
    
    def printWeight(self):
        print(self.wih.shape, self.wih)
        print(self.who.shape, self.who)
    
    # forward and backward
    def train(self, input_list, target_list):
        
        input = np.array(input_list, ndmin=2).T # 2차원으로 바꿔준다음에 transpose
        
        # input ->hidden
        hidden_input = np.dot(self.wih,input)
        hidden_output = scipy.special.expit(hidden_input)
        
        #h hidden -> output
        output_hidden = np.dot(self.who, hidden_output)
        final_output = scipy.special.expit(output_hidden
                                           
        # Get Error
        targets = np.array(targer_list , ndmin=2).T
        
        output_error = targets -final_outputs
        hidden_error = np.dot(self.who.T, output_error)
         
        # Update weight                                   
        self.who += self.lr * \
                            np.dot((output_error * final_output) * (1.0 -final_output), \
                            
                            np.transpose(hiddden_output))
        self.wih += self.lr * \
                            np.dot((output_error * final_output) * (1.0 -final_output), \
                            
                            np.transpose(input))
                                           
    # forward
    def inference(self, input_list):
        input = np.array(input_list, ndmin=2).T # 2차원으로 바꿔준다음에 transpose
        
        # input ->hidden
        hidden_input = np.dot(self.wih,input)
        hidden_output = scipy.special.expit(hidden_input)
        
        #h hidden -> output
        output_hidden = np.dot(self.who, hidden_output)
        final_output = scipy.special.expit(output_hidden)
        
        return hidden_output
    

SyntaxError: invalid syntax (<ipython-input-125-635cc0c6cf3a>, line 34)

In [116]:
net = MyNeuralNet(3, 4, 3 , 0.5)
net.printWeight()

(4, 3) [[ 0.32173243 -0.36632318  0.33820844]
 [-0.03987683 -0.36200617  0.36190651]
 [ 0.2566341   0.1498939  -0.27339238]
 [ 0.03492773  0.29592769 -0.01971328]]
(3, 4) [[-0.34758431 -0.37021262 -0.38778832  0.40401703]
 [-0.48565159  0.10054464  0.06515091 -0.38719409]
 [-0.49645688  0.05794473 -0.02413174 -0.38246685]]


In [124]:
net = MyNeuralNet(3, 3, 3 , 0.5)
net.inference([10,20,40])

NameError: name 'scipy' is not defined

In [ ]:
net = MyNeuralNet(3, 3, 3 , 0.5)
net.train([10, 20, 30, 40],[0.5,v0.2, 0.1])